name: BlanchardPA2019
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.19.5
  - scipy=1.5.3
  - matplotlib=3.3.4
  - joblib=1.0.0
  - nbclient=0.7.0
  - ipykernel=6.16.2

